accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"


urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
]

order/urls.py
from django.urls import path
from .views import PickupOrderView


app_name = "order"
urlpatterns = [
    path("pickup/", PickupOrderView.as_view(), name="pickup-order"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Cleanio{% endblock title %}</title>
    <link rel="icon" href="{% static 'assets/img/heading-img.png' %}" />
    <!-- CSS only -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'assets/css/bootstrap.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/css/owl.carousel.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/css/owl.theme.default.min.css' %}"
    />
    <link rel="stylesheet" href="{% static 'assets/css/slick.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/slick-theme.css' %}" />
    <!-- nice-select -->
    <link rel="stylesheet" href="{% static 'assets/css/nice-select.css' %}" />
    <!-- fancybox -->
    <link
      rel="stylesheet"
      href="{% static 'assets/css/jquery.fancybox.min.css' %}"
    />
    <link rel="stylesheet" href="{% static 'assets/css/aos.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'assets/css/fontawesome.min.css' %}"
    />
    <!-- style -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
    <!-- responsive -->
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}" />
    <!-- color -->
    <link rel="stylesheet" href="{% static 'assets/css/color.css' %}" />

    <style type="text/css" media="print">
      body { visibility: hidden; display: none }
  </style>

  </head>

  <body>
    <!-- preloader -->
    <div class="preloader">
      <div class="loader-6">
        <div class="set-one">
          <div class="circle"></div>
          <div class="circle"></div>
        </div>
        <div class="set-two">
          <div class="circle"></div>
          <div class="circle"></div>
        </div>
      </div>
    </div>
    <!-- preloader end -->

    <!--Header-->
    {% include "common/navbar/header.html" %}
    <!--/Header-->

    <!--block sections-->
    {% block header-sections %}{% endblock header-sections %}
    <!--block sections-->
    
    {% block content %}{% endblock content %}
    <!---->
    {% block modal %}{% endblock modal %}

    <!-- footer -->
    {% include "common/footer.html" %}
    <!-- footer -->

    <!---->

    {% comment %} modal {% endcomment %}

    <!-- popup -->
    <div class="box">
      <div class="flex-img">
        <div class="form-box">
          <div class="comment">
            <h2>Schedule a Pickup</h2>
            <div class="boder-bar"></div>
          </div>

          <form method="post" action="{% url 'order:pickup-order' %}" >
           {% csrf_token %}
            <div class="row">
              <div class="col-lg-6">
                <input
                  placeholder="Pick-Up Date"
                  type="text"
                  onfocus="(this.type = 'date')"
                  id="date"
                  type="text"
                  name="pickup_date"
                />
              </div>
              <div class="col-lg-6">
                <input
                  placeholder="Delivery Date"
                  type="text"
                  onfocus="(this.type = 'date')"
                  id="date"
                  type="text"
                  name="delivery_date"
                />
              </div>
              <div class="col-lg-6">
                {{pickup_form_class.full_name}}
              </div>
              <div class="col-lg-6">
                {{pickup_form_class.email}}
              </div>
              <div class="col-lg-6">
                {{pickup_form_class.phone}}
              </div>
              <div class="col-lg-6">
                {{pickup_form_class.address}}
              </div>
              
              <div class="col-lg-12">
                {{pickup_form_class.instructions}}
              </div>
              {% comment %} <a href="#" class="sec-btn">Book Order</a> {% endcomment %}
              <button class="sec-btn">Submit</button>
            </div>
          </form>
        </div>
        <img src="{% static 'assets/img/box.jpg' %}" alt="box" />
      </div>
      <div class="close"><i class="fa-solid fa-xmark"></i></div>
    </div>
    
    
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Login to account</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
              <form method="post" action="{% url 'accounts:login' %}">
                {% csrf_token %}
                <div class="mb-3">
                  <label for="exampleInputEmail1" class="form-label">Email address</label>
                  {{login_form.email}}
                  <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
                </div>
                <div class="mb-3">
                  <label for="exampleInputPassword1" class="form-label">Password</label>
                  {{login_form.password}}
                </div>
                <div class="mb-3 form-check">
                  <input type="checkbox" class="form-check-input" id="exampleCheck1">
                  <label class="form-check-label" for="exampleCheck1">Remember me</label>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#resetpassword">Reset Password</button>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="resetpassword" tabindex="-1" aria-labelledby="resetpasswordLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="resetpasswordLabel">Reset Password</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
              <form>
                <div class="mb-3">
                  <label for="exampleInputPassword1" class="form-label">Old Password</label>
                  <input type="password" class="form-control" id="exampleInputPassword1" aria-describedby="emailHelp">
                  <div id="emailHelp" class="form-text">One time password sent to your email</div>
                </div>
                <div class="mb-3">
                  <label for="exampleInputPassword1" class="form-label">New Password</label>
                  <input type="password" class="form-control" id="exampleInputPassword1">
                </div>
                <div class="flex items-center justify-between">
                <button type="submit" class="btn btn-primary">save changes</button>
                <button type="button" class="btn btn-danger"  data-bs-toggle="modal" data-bs-target="#exampleModal">cancel reset</button>
              </div>
              </form>
          </div>
        </div>
      </div>
    </div>
    
    
    <!-- popup end -->
    
    
    <!-- LIGHTBOX -->
    <div id="lightbox" class="lightbox clearfix">
      <div class="white_content">
          <a href="javascript:;" class="textright" id="close"><i class="fa-regular fa-circle-xmark"></i></a>
              <h1>Dry Cleaning & Laundry Experts</h1>
              <h4 class="des">Dry cleaning and laundry service, made to make life fresher</h4>
        <figure>
          <img src="{% static 'assets/img/desktop-menu-img.jpg' %}" alt="Desktop Menu Image">
        </figure>
        <h3>Get in touch</h3>
        <p class="num"><i>
              <svg height="112" viewBox="0 0 24 24" width="112" xmlns="http://www.w3.org/2000/svg"><g clip-rule="evenodd" fill="rgb(255255,255)" fill-rule="evenodd"><path d="m7 2.75c-.41421 0-.75.33579-.75.75v17c0 .4142.33579.75.75.75h10c.4142 0 .75-.3358.75-.75v-17c0-.41421-.3358-.75-.75-.75zm-2.25.75c0-1.24264 1.00736-2.25 2.25-2.25h10c1.2426 0 2.25 1.00736 2.25 2.25v17c0 1.2426-1.0074 2.25-2.25 2.25h-10c-1.24264 0-2.25-1.0074-2.25-2.25z"></path><path d="m10.25 5c0-.41421.3358-.75.75-.75h2c.4142 0 .75.33579.75.75s-.3358.75-.75.75h-2c-.4142 0-.75-.33579-.75-.75z"></path><path d="m9.25 19c0-.4142.33579-.75.75-.75h4c.4142 0 .75.3358.75.75s-.3358.75-.75.75h-4c-.41421 0-.75-.3358-.75-.75z"></path></g></svg>
            </i><a href="callto:{{telephone_contact}}">(+254) {{telephone_contact}}</p>
        <p class="num"><i>
            <svg version="1.1" xml:space="preserve" width="682.66669" height="682.66669" viewBox="0 0 682.66669 682.66669" xmlns="http://www.w3.org/2000/svg"><clipPath clipPathUnits="userSpaceOnUse"><path d="M 0,512 H 512 V 0 H 0 Z"></path></clipPath><g transform="matrix(1.3333333,0,0,-1.3333333,0,682.66667)"><g><g clip-path="url(#clipPath2333)"><g transform="translate(256,92)"><path d="m 0,0 c -126.964,143.662 -160,165.23 -160,240 0,88.366 71.634,160 160,160 88.365,0 160,-71.634 160,-160 C 160,165.854 130.212,147.337 0,0 Z" style="fill:none;stroke:#8cc63f;stroke-width:40;stroke-linecap:square;stroke-linejoin:miter;stroke-miterlimit:10;stroke-dasharray:none;stroke-opacity:1"></path></g><g transform="translate(316,372)"><path d="m 0,0 -80,-80 -40,40" style="fill:none;stroke:#8cc63f;stroke-width:40;stroke-linecap:square;stroke-linejoin:miter;stroke-miterlimit:10;stroke-dasharray:none;stroke-opacity:1"></path></g></g></g></g>
            </svg>
          </i>Jkuat Gate A, Juja Kiambu</p>
        <div class="social-medias">
            <a href="javascript:void(0)">Facebook</a>
            <a href="javascript:void(0)">Twitter</a>
            <a href="javascript:void(0)">Linkedin</a>
          </div>
      </div>
  </div>
<!-- LIGHTBOX END -->
    
    
    <!-- progress -->
<!-- progress -->
<div id="progress">
  <span id="progress-value"><i class="fa-solid fa-arrow-up"></i></span>
</div>
<!-- progress end -->
    
    <!-- jQuery -->
    <script src="{% static 'assets/js/jquery-3.6.0.min.js' %}"></script>
    <!-- Bootstrap Js -->
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/js/slick.min.js' %}"></script>
    <script src="{% static 'assets/js/aos.js' %}"></script>
    <script src="{% static 'assets/js/jquery.nice-select.min.js' %}"></script>
    <!-- fancybox -->
    <script src="{% static 'assets/js/jquery.fancybox.min.js' %}"></script>
    <script src="{% static 'assets/js/aos-data.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>

    


    <script>
          // Disable right-click
      document.addEventListener('contextmenu', (e) => e.preventDefault());
      
      function ctrlShiftKey(e, keyCode) {
        return e.ctrlKey && e.shiftKey && e.keyCode === keyCode.charCodeAt(0);
      }
      
      document.onkeydown = (e) => {
        // Disable F12, Ctrl + Shift + I, Ctrl + Shift + J, Ctrl + U
        if (
          event.keyCode === 123 ||
          ctrlShiftKey(e, 'I') ||
          ctrlShiftKey(e, 'J') ||
          ctrlShiftKey(e, 'C') ||
          (e.ctrlKey && e.keyCode === 'U'.charCodeAt(0))
        )
          return false;
      };
    </script>
    

  
    

  
  
    </body>
</html>
   

templates/contact.html
{% extends "base.html" %} {% load static %} {% load humanize %}


{% comment %}  {% endcomment %}
{% block header-sections %}

<section class="hero-section banner">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6">
        <div class="hero-text">
          <h2>Contact</h2>
          <h6>Dry cleaning and laundry service, made to make life fresher</h6>
        </div>
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="index.html">Home</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">Contact Us</li>
        </ol>
      </div>
      <div class="col-lg-6">
        <div class="hero-img">
          <img src="{% static 'assets/img/banner.jpg' %}" alt="img" />
        </div>
      </div>
    </div>
  </div>
  <div class="heroshaps-1"></div>
  <div class="heroshaps-2"></div>
</section>

{% endblock header-sections %}



{% block content %}
<section class="gap">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-md-6">
          <div class="contact-style">
            <i class="position-relative fa-solid fa-clock"></i>
            <h6 class="position-relative">Working Hours.</h6>
            <h4 class="position-relative">
              8.00 AM - 05.00 PM <span>Monday - Saturday</span>
            </h4>
          </div>
        </div>
        <div class="col-lg-4 col-md-6">
          <div class="contact-style two">
            <i class="position-relative">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 32 32"
                id="headphone"
              >
                <path
                  d="M18.6 22h-5.2c-.3 0-.5-.2-.5-.5s.2-.5.5-.5h5.2c.3 0 .5.2.5.5s-.2.5-.5.5zM16.6 24h-3.2c-.3 0-.5-.2-.5-.5s.2-.5.5-.5h3.2c.3 0 .5.2.5.5s-.2.5-.5.5zM7.5 24c-.8 0-1.5-.7-1.5-1.5v-6c0-.8.7-1.5 1.5-1.5s1.5.7 1.5 1.5v6c0 .8-.7 1.5-1.5 1.5zm0-8c-.3 0-.5.2-.5.5v6c0 .3.2.5.5.5s.5-.2.5-.5v-6c0-.3-.2-.5-.5-.5z"
                ></path>
                <path
                  d="M6.5 23h-2c-.8 0-1.5-.7-1.5-1.5v-4c0-.8.7-1.5 1.5-1.5h2c.3 0 .5.2.5.5v6c0 .3-.2.5-.5.5zm-2-6c-.3 0-.5.2-.5.5v4c0 .3.2.5.5.5H6v-5H4.5zM24.5 24c-.8 0-1.5-.7-1.5-1.5v-6c0-.8.7-1.5 1.5-1.5s1.5.7 1.5 1.5v6c0 .8-.7 1.5-1.5 1.5zm0-8c-.3 0-.5.2-.5.5v6c0 .3.2.5.5.5s.5-.2.5-.5v-6c0-.3-.2-.5-.5-.5z"
                ></path>
                <path
                  d="M27.5 23h-2c-.3 0-.5-.2-.5-.5v-6c0-.3.2-.5.5-.5h2c.8 0 1.5.7 1.5 1.5v4c0 .8-.7 1.5-1.5 1.5zM26 22h1.5c.3 0 .5-.2.5-.5v-4c0-.3-.2-.5-.5-.5H26v5zM18.5 31h-1c-.8 0-1.5-.7-1.5-1.5s.7-1.5 1.5-1.5h1c.8 0 1.5.7 1.5 1.5s-.7 1.5-1.5 1.5zm-1-2c-.3 0-.5.2-.5.5s.2.5.5.5h1c.3 0 .5-.2.5-.5s-.2-.5-.5-.5h-1z"
                ></path>
                <path
                  d="M21.5 30h-2c-.3 0-.5-.2-.5-.5s.2-.5.5-.5h2c3 0 5.5-2.5 5.5-5.5v-1c0-.3.2-.5.5-.5s.5.2.5.5v1c0 3.6-2.9 6.5-6.5 6.5zM26.4 13.5c-.8 0-1.4-.6-1.5-1.3C24.5 7.5 20.7 4 16 4s-8.5 3.5-9 8.2c-.1.7-.7 1.3-1.5 1.3-.4 0-.8-.2-1.1-.5-.3-.3-.4-.7-.4-1.2C4.6 5.7 9.8 1 16 1s11.4 4.7 11.9 10.9c0 .4-.1.8-.4 1.2-.2.2-.6.4-1.1.4zM16 3c5.2 0 9.5 3.9 10 9.1 0 .2.2.4.5.4.1 0 .3-.1.4-.2.1-.1.1-.2.1-.4C26.4 6.3 21.7 2 16 2S5.6 6.3 5 11.9c0 .1 0 .3.1.4.3.3.9.1.9-.2C6.5 6.9 10.8 3 16 3z"
                ></path>
                <path
                  d="M5.5 17c-.3 0-.5-.2-.5-.5v-3c0-.3.2-.5.5-.5s.5.2.5.5v3c0 .3-.2.5-.5.5zM26.5 17c-.3 0-.5-.2-.5-.5v-3c0-.3.2-.5.5-.5s.5.2.5.5v3c0 .3-.2.5-.5.5zM13.5 28c-.1 0-.2 0-.2-.1-.2-.1-.3-.3-.3-.4V26h-.5c-.8 0-1.5-.7-1.5-1.5v-4c0-.8.7-1.5 1.5-1.5h7c.8 0 1.5.7 1.5 1.5v4c0 .8-.7 1.5-1.5 1.5h-2.8l-2.9 1.9c-.1.1-.2.1-.3.1zm-1-8c-.3 0-.5.2-.5.5v4c0 .3.2.5.5.5h1c.3 0 .5.2.5.5v1.1l2.2-1.5c.1-.1.2-.1.3-.1h3c.3 0 .5-.2.5-.5v-4c0-.3-.2-.5-.5-.5h-7z"
                ></path>
              </svg>
            </i>
            <h6 class="position-relative">Phone No.</h6>
            <h4 class="position-relative">
              <a href="callto:{{telephone_contact}}">{{telephone_contact}}</a
              ><span>24/7 Support team</span>
            </h4>
          </div>
        </div>
        <div class="col-lg-4 col-md-6">
          <div class="contact-style mb-0">
            <i class="position-relative">
              <svg
                height="512"
                viewBox="0 0 32 32"
                width="512"
                xmlns="http://www.w3.org/2000/svg"
              >
                <g id="Layer_34" data-name="Layer 34">
                  <path
                    d="m30 9v14a3 3 0 0 1 -3 3h-22a3 3 0 0 1 -3-3v-14a2.87 2.87 0 0 1 .19-1l12.15 8.1a3 3 0 0 0 3.32 0l12.15-8.1a2.87 2.87 0 0 1 .19 1zm-13.45 5.43 12-8a3 3 0 0 0 -1.55-.43h-22a3 3 0 0 0 -1.54.44l12 8a1 1 0 0 0 1.09-.01z"
                  ></path>
                </g>
              </svg>
            </i>
            <h6 class="position-relative">Email Address.</h6>
            <h4 class="position-relative">
              <a href="mailto:{{email_contact}}">{{email_contact}}</a
              ><span>General Query</span>
            </h4>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section>
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <div class="heading two contact-heading">
            <p>MEET OUR PROFESSIONALS</p>
            <h2>We'd Love to Hear From You!</h2>
            <h6>
              Dry Cleaning & Laundry Expers with Collection and Delivery in 24
              hours
            </h6>
            <div class="star-rating">
              <h4>#1 Customer-Rated</h4>
              <h5>in categories dry cleaning, laundry & Ironing Service</h5>
              <ul>
                <li><i class="fa-solid fa-star"></i></li>
                <li><i class="fa-solid fa-star"></i></li>
                <li><i class="fa-solid fa-star"></i></li>
                <li><i class="fa-solid fa-star"></i></li>
                <li><i class="fa-solid fa-star"></i></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-6">
          <form class="content-form">
            <input type="text" name="Name" placeholder="Full Name" />
            <input type="text" name="Email" placeholder="Email Address" />
            <input type="text" name="Phone" placeholder="Phone No" />
            <textarea placeholder="Your Message"></textarea>
            <button class="sec-btn">Send Message</button>
          </form>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

templates/faq.html
{% extends "base.html" %} {% load static %} {% load humanize %} 


<!---->


{% block header-sections %}

<section class="hero-section banner">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6">
        <div class="hero-text">
          <h2>Faq</h2>
          <h6>Dry cleaning and laundry service, made to make life fresher</h6>
        </div>
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="index.html">Home</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">Contact Us</li>
        </ol>
      </div>
      <div class="col-lg-6">
        <div class="hero-img">
          <img src="{% static 'assets/img/banner.jpg' %}" alt="img" />
        </div>
      </div>
    </div>
  </div>
  <div class="heroshaps-1"></div>
  <div class="heroshaps-2"></div>
</section>

{% endblock header-sections %}
<!---->
{% block content %}

<section style="padding:50px 0px !important;">
  <div class="container">
    <div class="heading">
      <img src="{% static 'assets/img/heading-img.png' %}" alt="heading-img" />
      <p>laundry faq's</p>
      <h2>Laundry Helpful Faq's</h2>
    </div>
    <div class="accordion">
      <div class="accordion-item">
        <a href="#" class="heading">
          <div class="icon"></div>
          <div class="title">Dry cleaning worth the cost?</div>
        </a>

        <div class="content">
          <p>
            Dry cleaning is always gently takes about 3-4 hours on average. The
            cleaning time depends on the material type, garment dirtiness, and
            other things.er, but for your more durable.
          </p>
        </div>
      </div>

      <div class="accordion-item active">
        <a href="#" class="heading">
          <div class="icon"></div>
          <div class="title">How long does dry clean take?</div>
        </a>

        <div class="content" style="display: block">
          <p>
            Dry cleaning is always gently takes about 3-4 hours on average. The
            cleaning time depends on the material type, garment dirtiness, and
            other things.er, but for your more durable.
          </p>
        </div>
      </div>

      <div class="accordion-item">
        <a href="#" class="heading">
          <div class="icon"></div>
          <div class="title">Best Dry Cleaners near me?</div>
        </a>

        <div class="content">
          <p>
            Dry cleaning is always gently takes about 3-4 hours on average. The
            cleaning time depends on the material type, garment dirtiness, and
            other things.er, but for your more durable.
          </p>
        </div>
      </div>

      <div class="accordion-item">
        <a href="#" class="heading">
          <div class="icon"></div>
          <div class="title">Does dry cleaning get rid of smell?</div>
        </a>

        <div class="content">
          <p>
            Dry cleaning is always gently takes about 3-4 hours on average. The
            cleaning time depends on the material type, garment dirtiness, and
            other things.er, but for your more durable.
          </p>
        </div>
      </div>

      <div class="accordion-item">
        <a href="#" class="heading">
          <div class="icon"></div>
          <div class="title">How does gold dry cleaners work?</div>
        </a>

        <div class="content">
          <p>
            Dry cleaning is always gently takes about 3-4 hours on average. The
            cleaning time depends on the material type, garment dirtiness, and
            other things.er, but for your more durable.
          </p>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}